apiVersion: batch/v1
kind: Job
metadata:
  name: guidellm-benchmark-job
  namespace: rhaiis
spec:
  template:
    spec:
      containers:
      - name: guidellm
        image: ghcr.io/neuralmagic/guidellm:latest
        env:
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-secret 
                key: HUGGING_FACE_TOKEN           
          - name: HF_HOME
            value: /tmp/huggingface_cache
        command: ["guidellm"]
        args:
          - "benchmark"
          - "--target"
          - "http://rhaiis-runner-service.rhaiis.svc.cluster.local:8000"
          - "--model"
          - "RedHatAI/DeepSeek-R1-Distill-Qwen-1.5B-quantized.w4a16"
          - "--processor"
          - "RedHatAI/DeepSeek-R1-Distill-Qwen-1.5B-quantized.w4a16"
          - "--data"
          - "{"prompt_tokens":512,"output_tokens":128}"
          - "--rate-type"
          - "sweep"
          - "--max-seconds"
          - "30"
          - "--output-path"
          - "/results/output.json"
        volumeMounts:
        - name: results-volume
          mountPath: /results
      volumes:
      - name: results-volume
        persistentVolumeClaim:
          claimName: guidellm-results-pvc
      restartPolicy: Never
  backoffLimit: 1
