apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhaiis-runner-pvc
  labels:
    app: rhaiis-runner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: <Your Storage Class for storing LLM models>
